routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home','HomeController@example');

Route:: get('/','FrontController@index')->name('index')->middleware('guest');




Route::get('/logout','auth\LoginController@logout')->name('logout');
Route::get('/index/login','auth\LoginController@index')->name('index.login');
Route::get('/index/signup','auth\RegisterController@index')->name('index.signup');
Route::post('/index/hacker/create','auth\RegisterController@createHacker')->name('index.create.hacker');
Route::post('/index/business/create','auth\RegisterController@createBusiness')->name('index.create.business');
Route::post('/index/login/match','auth\LoginController@adminLogin')->name('index.login.match');
// Route::namespace('auth')->group( function()
//   {
//      Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
//      Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//       Route::get(' password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
//       Route::post(' password/reset','ResetPasswordController@reset')->name('password.update');

//   });
Auth::routes(['verify'=>true]);
//front side blog post for guest user
Route::get('front/post','BlogController@showpost')->name('post');
Route::get('front/singlepost/{post}','BlogController@singlepost')->name('singlepost');
Route::get('front/post/category/{category}','BlogController@category')->name('post.category');
   //front side gallery rouyte here
Route::get('gallaery','GalleryController@showgallerycategory')->name('gallery');
Route::get('gallaery/{image}','GalleryController@showgallerycategoryimage')->name('gallery.image');
Route::get('contactus','FrontController@contactus')->name('contactus');
Route::post('contactus/store','FrontController@contactStore')->name('contactus.store');
Route::get('business','FrontBusinessController@businessindex')->name('business.index');
Route::get('hacker','FrontHackerController@hackerindex')->name('hacker.index');




  //hacker  route 

Route::prefix('hacker')->namespace('hacker')->middleware('hacker')->name('hacker.')->group(function()
 {
         Route::get('/dashboard', 'DashboardController@hackerindex')->name('dashboard');
         // **profile of hacker**//
         Route::get('/profile', 'HackerController@profile')->name('profile');
         Route::post('/profile/update/{id}', 'HackerController@update')->name('profile.update');
         //** hacker post **//
         Route::get('/post','BlogController@showpost')->name('post');
         Route::get('/singlepost/{post}','BlogController@singlepost')->name('singlepost');
         Route::get('/post/category/{category}','BlogController@category')->name('post.category');
         Route::resource('/create/posts','CreatePostController');
         //event and bounty//
         Route::get('/event/','BountyController@show')->name('event.show');
         Route::get('/event/detail/{detail}','BountyController@showdetail')->name('event.show.detail');
         Route::get('/event/detail/with/category/{category}','BountyController@showcategorydetail')->name('event.show.category.detail');
         Route::get('/closed/bounty','BountyController@closedbounty')->name('closed.bounty');
         //download file
         Route::get('/file/download/{id}','BountyController@download')->name('file.download');

         Route::post('/report/send','BountyController@sendReport')->name('report.send');
         Route::get('/mark/notification/','BountyController@check_read_notification');


});


// admin routes here

Route::prefix('admin')->namespace('admin')->group(function()
{ 
 Route::middleware('redirectToDashboard')->group(function()
    {
     Route::get('/show/login','LoginController@showloginform')->name('admin.show.login');
	 	 Route::post('/login','LoginController@login')->name('admin.login');
	   Route::get('/show/signup','LoginController@showsignupform')->name('admin.show.signup');
	   Route::post('/signup','LoginController@signup')->name('admin.signup');
   });
     Route::get('/logout','LoginController@logout')->name('admin.logout');

     Route::middleware('admin')->name('admin.')->group(function()
     {
       Route::get('/dashboard','DashboardController@show')->name('dashboard');
       Route::resource('categories','CategoryController');
       Route::resource('posts','PostController');
       Route::get('/pending/post','PostController@pendingpost')->name('pending.post');
       Route::post('/approve/post/{post}','PostController@approvepost')->name('approve.post');
       Route::post('/trash/posts/{post}','PostController@trash')->name('trash.post');
       Route::get('/show/trash','PostController@showtrash')->name('show.trash');
       Route::post('/restore/post/{post}','PostController@restorepost')->name('restore.post');
       //bounty category
       Route::resource('category/bounties','BountyCategoryController');
       Route::get('active/bounty','BountyController@showactivebunty')->name('active.bounty');
       Route::get('pending/bounty','BountyController@showpendingbunty')->name('pending.bounty');
       Route::get('/closed/bounty','BountyController@showexpiredbunty')->name('closed.bounty');
       Route::post('approve/bounty/{bounty}','BountyController@approve')->name('approve.bounty');
       Route::post('multiple/delete','BountyController@massdelete')->name('mass.bounty.delete');
       Route::get('single/delete/{id}','BountyController@singledelete')->name('single.bounty.delete');
       // Route::get('bounties/show','BountyController@index')->name('admin.bounties.index');
       //gallaery here
       Route::resource('gallery-category','GalleryCategoryController');
       // Route::resource('gallery-image','GalleryImageController');
       Route::post('admin/gallery-image/store/{id}','GalleryImageController@store')->name('gallery-image.store');
       Route::get('admin/gallery-image/{gallery_image}','GalleryImageController@show')->name('gallery-image.show');
       Route::post('admin/gallery-image/{gallery_image}','GalleryImageController@destroy')->name('gallery-image.destroy');

   });


});






 // business section route here

  Route::prefix('business')->namespace('business')->name('business.')->middleware('business')->group(function()
  {

     Route::get('/dashboard','DashboardController@index')->name('dashboard');
     Route::get('/profile','BusinessController@profile')->name('profile');
     Route::post('/profile/update/{id}', 'BusinessController@update')->name('profile.update');
    // business post
     Route::get('/post','BlogController@showpost')->name('post');
     Route::get('/singlepost/{post}','BlogController@singlepost')->name('singlepost');
     Route::get('/post/category/{category}','BlogController@category')->name('post.category');
     Route::resource('/create/posts','CreatePostController');
    //business event
     Route::get('/event','EventController@show')->name('event');
     Route::get('/mark/notification/','EventController@check_read_notification');
     Route::get('/rate','EventController@RatingStore');
     Route::get('/rate/check','EventController@CheckIfAlready');

     Route::get('show/hacker/profile/{id}','EventController@showhackerprofile')->name('show.hacker.profile'); 
     Route::post('post/bounty','BountyController@store')->name('bounty.store');

     Route::get('/report/detail/{id}','EventController@showReportDetails')->name('reports.detail');
     Route::get('/report/delete/{id}','EventController@deletereport')->name('delete.report');
     Route::post('/report/delete/mass','EventController@deleteMassreport')->name('delete.mass-report');  



});

 // business route end here



//post is public so rote is made publuc







// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\GalleryCategory;
use App\GalleryImage;

class GalleryController extends Controller
{
     public function showgallerycategory()
       {
       	 return view('front.gallery.gallery-category')->with('categories',GalleryCategory::all());
       }

       public function  showgallerycategoryimage($slug)
        {   $category=GalleryCategory::where('slug',$slug)->first();

                 
           $image=GalleryImage::where('gallery_category_id',$category->id)->get();
        
        	
        	return view('front.gallery.image')->with('category',$category)->with('images',$image);
        }
}

resources/views/admin/gallery/edit-gallery-category.blade.php
@extends('layouts.admin.app')


@section('content')
<div class="clearfix"></div>
<div id="right-panel" class="right-panel">

<div class="content"> 

       
            <div class="animated fadeIn">
                <div class="row">
                    
                    <div class="col-lg-10  mx-auto">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Category edit</strong>
                               
                            </div>
                            <div class="card-body">
                                <form method="post" action="{{ route('admin.gallery-category.update',$category->id) }}" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')

                                   <div class="form-group">
                                    <label for="name">title name</label>
                                    <input type="text" name="title" class="form-control " value="{{$category->name}}">
                                    @foreach($errors->get('title') as $message )
                                   <small class="red ">***{{$message}}</small> 
                                   @endforeach
                                   </div>
                                  

                                     <label for="name">Change Cover image</label> 
                                   
                                   <div class="form-group">
                                     <img src="{{asset('gallery/cover/'.$category->cover_image)}}" class="" height="150" width="150">
                                     
                                    <input type="file" name="cover_image" class="form-control">
                                     @foreach($errors->get('cover_image') as $message )
                                   <small class="red ">***{{$message}}</small> 
                                   @endforeach
                                   </div>
                                   <input   type="submit"  class="btn btn-primary d-lg-inline-block" value="update">
                              
                        </div>
                    </div>
                </div>

              
              </div>
    </div><!-- .animated -->
</div><!-- .content -->
</div>






@endsection


@section('css')

<style type="text/css">
    .form-control {
                 
               width: 60%;

                 }
                .red{
                    color:red;
                    font-style: italic;
                }
</style>
@endsection

resources/views/admin/gallery/gallery-category.blade.php
@extends('layouts.admin.app')


@section('content')
<div class="clearfix"></div>
<div id="right-panel" class="right-panel">

<div class="content">

 @if($errors->any())

         
           
              @foreach($errors->all() as $error)
                 <div class="alert alert-danger" role="alert">
                        {{ $error}}
                 </div>
              @endforeach
          
          
         @endif

        @if(session()->has('success'))
           <div class="alert alert-success" role="alert">
                        {{ session()->get('success')}}
                 </div>
        @endif
         @if(session()->has('error'))
           <div class="alert alert-danger" role="alert">
                        {{ session()->get('error')}}
                 </div>
        @endif
     
            <div class="animated fadeIn">
                <div class="row">
                    
                    <div class="col-lg-10  mx-auto">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Gallery title table</strong>
                                <button class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal">Add title to gallery</button>
                            </div>
                            <div class="card-body">
                                <table class="table">
                                    <thead>
                                        <tr>
                                          <th >#</th>
                                          <th >title Name</th>
                                          <th>cover Image</th>
                                          <th>action</th>
                                        
                                      </tr>
                                  </thead>
                                  <tbody>

                                    @foreach($categories as $category)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $category->name }}</td>
                                        <td><img src="{{ asset('gallery/cover/'.$category->cover_image)}}" height="50" width="50"></td>
                                        <td><a class=" btn btn-secondary btn-sm d-lg-inline-block"  href="{{route('admin.gallery-category.edit',$category->id) }}">edit</a>
                                          <a class=" btn btn-primary btn-sm d-lg-inline-block"  href="{{route('admin.gallery-image.show',$category->id) }}">view</a>
                                     
                                
                                          <form method="post" action="{{ route('admin.gallery-category.destroy',$category->id)}}" class="d-lg-inline-block">
                                            @csrf
                                            @method('DELETE')
                                        <input type="submit" class=" btn btn-danger btn-sm d-inline-block "  value="Delete">
                                     </form>
                                      </td>
                                        
                                        
                                    </tr>
                                    @endforeach
                                   
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

              
              </div>
    </div><!-- .animated -->
</div><!-- .content -->
</div>







<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{{route('admin.gallery-category.store')}}" enctype="multipart/form-data">
        @csrf
      <div class="modal-body">
        
        
            <div class="form-group">
              <label for="name">Title</label>
              <input type="text" name="title" class="form-control">
              
            </div>
            <div class="form-group">
              <label for="name">Cover image</label>
              <input type="file" name="cover_image" class="form-control">
              
            </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add</button>
      </div>
    </form>
    </div>
  </div>
</div>




@endsection




@section('script')


<script type="text/javascript">
  
$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})
</script>
@endscript

resources/views/admin/gallery/gallery-image.blade.php
@extends('layouts.admin.app')


@section('content')

<div id="right-panel" class="right-panel">

<div class="content pt-0">

 @if($errors->any())

         
           
              @foreach($errors->all() as $error)
                 <div class="alert alert-danger" role="alert">
                        {{ $error}}
                 </div>
              @endforeach
          
          
         @endif
        @if(session()->has('success'))
           <div class="alert alert-success" role="alert">
                        {{ session()->get('success')}}
                 </div>
        @endif
     
            <div class="animated fadeIn card">
              <div class="card-header">
                      <h4>{{$category->name}}</h4>
                      <span class="float-right"><button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">upload photo</button></span>
                      </h4>
                  </div>
                  <div class="card-body">
                <div class="row ">
                    
                    @forelse($galleries as $gallery)

                    <div class="col-md-4 contain mt-4">
                      <img src="{{asset('gallery/image/'.$gallery->image)}}">
                      
                 
  
                    <span class="but">
                      <form method="post" action="{{route('admin.gallery-image.destroy',$gallery->id)}}">
                        @csrf

                        <button type="submit">Delete</button>
                       </form> 
                    </span>
                   

                    </div>
                      @empty
                       <center>  no image in this title you can upload by clicking top right button </center>

                      @endforelse

                   
                    
                    
                    
                  </div>

              
              </div>
    </div><!-- .animated -->
</div><!-- .content -->
</div>







<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{{route('admin.gallery-image.store',$category->id)}}" enctype="multipart/form-data">
        @csrf
      
      <div class="modal-body">
        
        
            <div class="form-group">
              <label for="name">Cover image</label> 
              <input type="file" name="image[]" class="form-control" multiple>
              
            </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add</button>
      </div>
    </form>
    </div>
  </div>
</div>




@endsection




@section('script')


<script type="text/javascript">
  
$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})
</script>
@endscript

@section('css')

<style>
  .contain {
  position: relative;
  margin-top: 0px;
  width: 250px;
  height: 250px;
}





 .contain img {
  position: absolut;
  width: 260;
  height: 260px;
  left: 0;
}



.contain:hover .tit {
  top: 100px;
}

.but{
  position: absolute;
  width: 250px;
  left:20;
  top: 150  ;
  text-align: center;
  opacity: 0;
  transition: opacity .35s ease;
}

.but button {
  width: 200px;
  padding: 12px 48px;
  text-align: center;
  color: white;
  border: solid 2px white;
  z-index: 1;

    background-color: Transparent;
 
}

.contain:hover .but {
  opacity: 1;
}

</style>
@endsection