routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home','HomeController@example');

Route:: get('/','FrontController@index')->name('index')->middleware('guest');




Route::get('/logout','auth\LoginController@logout')->name('logout');
Route::get('/index/login','auth\LoginController@index')->name('index.login');
Route::get('/index/signup','auth\RegisterController@index')->name('index.signup');
Route::post('/index/hacker/create','auth\RegisterController@createHacker')->name('index.create.hacker');
Route::post('/index/business/create','auth\RegisterController@createBusiness')->name('index.create.business');
Route::post('/index/login/match','auth\LoginController@adminLogin')->name('index.login.match');
// Route::namespace('auth')->group( function()
//   {
//      Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
//      Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//       Route::get(' password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
//       Route::post(' password/reset','ResetPasswordController@reset')->name('password.update');

//   });
Auth::routes(['verify'=>true]);
//front side blog post for guest user
Route::get('front/post','BlogController@showpost')->name('post');
Route::get('front/singlepost/{post}','BlogController@singlepost')->name('singlepost');
Route::get('front/post/category/{category}','BlogController@category')->name('post.category');
   //front side gallery rouyte here
Route::get('gallaery','GalleryController@showgallerycategory')->name('gallery');
Route::get('gallaery/{image}','GalleryController@showgallerycategoryimage')->name('gallery.image');
Route::get('contactus','FrontController@contactus')->name('contactus');
Route::post('contactus/store','FrontController@contactStore')->name('contactus.store');
Route::get('business','FrontBusinessController@businessindex')->name('business.index');
Route::get('hacker','FrontHackerController@hackerindex')->name('hacker.index');




  //hacker  route 

Route::prefix('hacker')->namespace('hacker')->middleware('hacker')->name('hacker.')->group(function()
 {
         Route::get('/dashboard', 'DashboardController@hackerindex')->name('dashboard');
         // **profile of hacker**//
         Route::get('/profile', 'HackerController@profile')->name('profile');
         Route::post('/profile/update/{id}', 'HackerController@update')->name('profile.update');
         //** hacker post **//
         Route::get('/post','BlogController@showpost')->name('post');
         Route::get('/singlepost/{post}','BlogController@singlepost')->name('singlepost');
         Route::get('/post/category/{category}','BlogController@category')->name('post.category');
         Route::resource('/create/posts','CreatePostController');
         //event and bounty//
         Route::get('/event/','BountyController@show')->name('event.show');
         Route::get('/event/detail/{detail}','BountyController@showdetail')->name('event.show.detail');
         Route::get('/event/detail/with/category/{category}','BountyController@showcategorydetail')->name('event.show.category.detail');
         Route::get('/closed/bounty','BountyController@closedbounty')->name('closed.bounty');
         //download file
         Route::get('/file/download/{id}','BountyController@download')->name('file.download');

         Route::post('/report/send','BountyController@sendReport')->name('report.send');
         Route::get('/mark/notification/','BountyController@check_read_notification');


});


// admin routes here

Route::prefix('admin')->namespace('admin')->group(function()
{ 
 Route::middleware('redirectToDashboard')->group(function()
    {
     Route::get('/show/login','LoginController@showloginform')->name('admin.show.login');
	 	 Route::post('/login','LoginController@login')->name('admin.login');
	   Route::get('/show/signup','LoginController@showsignupform')->name('admin.show.signup');
	   Route::post('/signup','LoginController@signup')->name('admin.signup');
   });
     Route::get('/logout','LoginController@logout')->name('admin.logout');

     Route::middleware('admin')->name('admin.')->group(function()
     {
       Route::get('/dashboard','DashboardController@show')->name('dashboard');
       Route::resource('categories','CategoryController');
       Route::resource('posts','PostController');
       Route::get('/pending/post','PostController@pendingpost')->name('pending.post');
       Route::post('/approve/post/{post}','PostController@approvepost')->name('approve.post');
       Route::post('/trash/posts/{post}','PostController@trash')->name('trash.post');
       Route::get('/show/trash','PostController@showtrash')->name('show.trash');
       Route::post('/restore/post/{post}','PostController@restorepost')->name('restore.post');
       //bounty category
       Route::resource('category/bounties','BountyCategoryController');
       Route::get('active/bounty','BountyController@showactivebunty')->name('active.bounty');
       Route::get('pending/bounty','BountyController@showpendingbunty')->name('pending.bounty');
       Route::get('/closed/bounty','BountyController@showexpiredbunty')->name('closed.bounty');
       Route::post('approve/bounty/{bounty}','BountyController@approve')->name('approve.bounty');
       Route::post('multiple/delete','BountyController@massdelete')->name('mass.bounty.delete');
       Route::get('single/delete/{id}','BountyController@singledelete')->name('single.bounty.delete');
       // Route::get('bounties/show','BountyController@index')->name('admin.bounties.index');
       //gallaery here
       Route::resource('gallery-category','GalleryCategoryController');
       // Route::resource('gallery-image','GalleryImageController');
       Route::post('admin/gallery-image/store/{id}','GalleryImageController@store')->name('gallery-image.store');
       Route::get('admin/gallery-image/{gallery_image}','GalleryImageController@show')->name('gallery-image.show');
       Route::post('admin/gallery-image/{gallery_image}','GalleryImageController@destroy')->name('gallery-image.destroy');

   });


});






 // business section route here

  Route::prefix('business')->namespace('business')->name('business.')->middleware('business')->group(function()
  {

     Route::get('/dashboard','DashboardController@index')->name('dashboard');
     Route::get('/profile','BusinessController@profile')->name('profile');
     Route::post('/profile/update/{id}', 'BusinessController@update')->name('profile.update');
    // business post
     Route::get('/post','BlogController@showpost')->name('post');
     Route::get('/singlepost/{post}','BlogController@singlepost')->name('singlepost');
     Route::get('/post/category/{category}','BlogController@category')->name('post.category');
     Route::resource('/create/posts','CreatePostController');
    //business event
     Route::get('/event','EventController@show')->name('event');
     Route::get('/mark/notification/','EventController@check_read_notification');
     Route::get('/rate','EventController@RatingStore');
     Route::get('/rate/check','EventController@CheckIfAlready');

     Route::get('show/hacker/profile/{id}','EventController@showhackerprofile')->name('show.hacker.profile'); 
     Route::post('post/bounty','BountyController@store')->name('bounty.store');

     Route::get('/report/detail/{id}','EventController@showReportDetails')->name('reports.detail');
     Route::get('/report/delete/{id}','EventController@deletereport')->name('delete.report');
     Route::post('/report/delete/mass','EventController@deleteMassreport')->name('delete.mass-report');  



});

 // business route end here



//post is public so rote is made publuc







// Route::get('/home', 'HomeController@index')->name('home');

app/Bounty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Bounty extends Model
{

	  protected $fillable=['title','image','deadline','description','reward','bounty_category_id','user_id','status','file','url'];
       public function category()
          {
          	return $this->belongsTo(BountyCategory::class,'bounty_category_id');
          }

          public function user()
           {
           	 return $this->belongsTo(User::class,'user_id');
           }

      public function getDeadlineAttribute($data)
        {
         return $data;
        }

        
}
	

app/Http/Controllers/Admin/BountyController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Bounty;

class BountyController extends Controller
{
    

      public function showactivebunty()
        {     $currentDate = date('Y-m-d');
        	 $data=Bounty::where('status','active')
                          ->whereDate('deadline', '>', $currentDate)
                          ->paginate(9);
        	  return view('admin.bounty.active-bounty')->with('activebounties',$data);
        }

        public function showexpiredbunty()
        {   
             $currentDate = date('Y-m-d');
             $data=Bounty::where('status','active')
                           ->whereDate('deadline', '<', $currentDate)
                           ->paginate(9);
              return view('admin.bounty.closed-bounty')->with('activebounties',$data);
        }

        public function showpendingbunty()
        {
        	 $data=Bounty::where('status','pending')->paginate(9);
        	  return view('admin.bounty.pending-bounty')->with('activebounties',$data);
        }

        public function approve(Bounty $bounty)
        { 

            $bounty->status='active';
            $bounty->save();
             session()->flash('success','Bounty has been successfuly appeoved');
            return redirect()->back();

        }

        public function massdelete(Request $request)
        { 
            $this->validate($request,[
              'del'=>'required'
            ]);

            $id=$request->del;
            Bounty::whereIn('id',$id)->delete();

            session()->flash('success','multiple Deleted  successfully');
            return redirect()->back();
        

        }

        public function singledelete(Bounty $id)
         {
                $id->delete();
                session()->flash('success','Deleted successfully');
                return redirect()->back();

         }

        
}

app/Http/Controllers/BountyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BountyController extends Controller
{
       
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('front.hacker.event');
    }



// this part is for sidebar in admin side
     
 
}

app/Http/Controllers/business/BountyController.php
<?php

namespace App\Http\Controllers\Business;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Bounty;
use Auth;

class BountyController extends Controller
{
     
      public function store(Request $request)
         {  
                 
                
               if($request->has('dropdown'))
               { 
               	 $ruleweb=$ruleapk=$ruleexe=$ruledrive='';
               	 $url=$files= $file_names="";
               	 if($request->dropdown=='1' )
               	  {
               	      $ruleweb='regex:/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/';
               	      $url=$request->website;

               	                     	  }
               	  else if($request->dropdown=='2')
               	  {
               	  	  $ruleexe='required';
               	  	 
               	  }
               	  else if ($request->dropdown=='3')
               	  {
                     $ruleapk='required';
                      

                     
               	  }
               	    else if ($request->dropdown=='4')
               	    {
               	    	$ruledrive='regex:/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?/';
               	    	 $url=$request->drive;
               	    }
               }





         	  $rule=[
         	  	     'website' =>$ruleweb,
                     'title'=>'required',
                     'description'=>'required',
                     'image'=>'mimes:jpeg,png,jpg,gif,svg|max:2048|required',
                     'deadline'=>'required',
                     'dropdown'=>'required',
                     'reward'=>'numeric',
                     'apk'=>$ruleapk,
                      'exe'=>$ruleexe,
                       'drive'=>$ruledrive
         	  ];
         	  $message=[
                    'numeric'=>'Amount must be numeric',
                    'exe.mimes'=>'plz enter exe file',
                    'apk.required'=>'plz enter your apk file ',
                    'apk.mimes'=>'plz enter apk file',
         	  ];
               $this->validate($request,$rule,$message);

             if($request->hasFile('image')) 
             {
            $file = $request->file('image');
            $file_name = time()."_".$file->getClientOriginalName();
            $file_location = public_path('bounty/img');

            $file->move($file_location, $file_name);
               
            
           }
               if($request->apk)
                   {
                   	  
                   	 $files = $request->file('apk');
                     $file_names =$files->getClientOriginalName();
                     $file_location = public_path('bounty/file');

                     $files->move($file_location, $file_names);
                   }
                  elseif($request->exe)
                  { 
                  	$files = $request->file('exe');
                    $file_names =$files->getClientOriginalName();
                     $file_location = public_path('bounty/file');

                     $files->move($file_location, $file_names);
                  }
           	        
                     

          
           Bounty::create([
           	          'title'=>$request->title,
           	          'description'=>$request->description,
           	          'reward'=>$request->reward,
           	          'deadline'=>$request->deadline,
           	          'reward'=>$request->reward,
           	          'bounty_category_id'=>$request->dropdown,
           	          'image'=>$file_name,
           	          'status'=>'pending',
           	          'user_id'=>Auth::user()->id,
           	          'url'=>$url,
           	           'file'=> $file_names,



           ]);

          session()->flash('success','bounty added successfully');
          return redirect(route('business.event'));



         }

}

resources/views/admin/bounty/category.blade.php
@extends('layouts.admin.app')
@section('content')
<div class="clearfix"></div>
<div id="right-panel" class="right-panel">
    <div class="content">
        <div class="animated fadeIn">
            @if(session()->has('success'))
            <div class="alert alert-success" role="alert">
                {{ session()->get('success')}}
            </div>
            @endif
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Table Head</strong>
                            <button class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal">Add category</button>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Category Name</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($categories as $category)
                                    <tr>
                                        <th scope="row">{{$loop->iteration}}</th>
                                        <td>{{$category->name}}</td>
                                        <td><a class=" btn btn-secondary btn-sm d-lg-inline-block" href="{{route('admin.bounties.edit',$category->id) }}">edit</a>
                                            <form method="post" action="{{ route('admin.bounties.destroy',$category->id)}}" class="d-lg-inline-block">
                                                @csrf
                                                @method('DELETE')
                                                <input type="submit" class=" btn btn-danger btn-sm d-inline-block " value="Delete">
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- .animated -->
    </div><!-- .content -->
</div>
-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{{route('admin.bounties.store')}}">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Category</label>
                        <input type="text" name="name" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('css')
@endsection
@section('script')
<script type="text/javascript">
$('#myModal').on('shown.bs.modal', function() {
    $('#myInput').trigger('focus')
})

</script>
@endsection

resources/views/admin/bounty/edit-category.blade.php
@extends('layouts.admin.app')
@section('content')
@section('title')
  Edit bounty
@endsection
<div class="clearfix"></div>
<div id="right-panel" class="right-panel">
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-lg-10  mx-auto">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Category edit</strong>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{{ route('admin.bounties.update',$categories->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="name">Category</label>
                                    <input type="text" name="name" class="form-control " value="{{$categories->name}}">
                                </div>
                                <input type="submit" class="btn btn-primary d-lg-inline-block" value="update">
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- .animated -->
    </div><!-- .content -->
</div>
@endsection
@section('css')
<style type="text/css">
.form-control {

    width: 60%;

}

</style>
@endsection