routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home','HomeController@example');

Route:: get('/','FrontController@index')->name('index')->middleware('guest');




Route::get('/logout','auth\LoginController@logout')->name('logout');
Route::get('/index/login','auth\LoginController@index')->name('index.login');
Route::get('/index/signup','auth\RegisterController@index')->name('index.signup');
Route::post('/index/hacker/create','auth\RegisterController@createHacker')->name('index.create.hacker');
Route::post('/index/business/create','auth\RegisterController@createBusiness')->name('index.create.business');
Route::post('/index/login/match','auth\LoginController@adminLogin')->name('index.login.match');
// Route::namespace('auth')->group( function()
//   {
//      Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
//      Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//       Route::get(' password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
//       Route::post(' password/reset','ResetPasswordController@reset')->name('password.update');

//   });
Auth::routes(['verify'=>true]);
//front side blog post for guest user
Route::get('front/post','BlogController@showpost')->name('post');
Route::get('front/singlepost/{post}','BlogController@singlepost')->name('singlepost');
Route::get('front/post/category/{category}','BlogController@category')->name('post.category');
   //front side gallery rouyte here
Route::get('gallaery','GalleryController@showgallerycategory')->name('gallery');
Route::get('gallaery/{image}','GalleryController@showgallerycategoryimage')->name('gallery.image');
Route::get('contactus','FrontController@contactus')->name('contactus');
Route::post('contactus/store','FrontController@contactStore')->name('contactus.store');
Route::get('business','FrontBusinessController@businessindex')->name('business.index');
Route::get('hacker','FrontHackerController@hackerindex')->name('hacker.index');




  //hacker  route 

Route::prefix('hacker')->namespace('hacker')->middleware('hacker')->name('hacker.')->group(function()
 {
         Route::get('/dashboard', 'DashboardController@hackerindex')->name('dashboard');
         // **profile of hacker**//
         Route::get('/profile', 'HackerController@profile')->name('profile');
         Route::post('/profile/update/{id}', 'HackerController@update')->name('profile.update');
         //** hacker post **//
         Route::get('/post','BlogController@showpost')->name('post');
         Route::get('/singlepost/{post}','BlogController@singlepost')->name('singlepost');
         Route::get('/post/category/{category}','BlogController@category')->name('post.category');
         Route::resource('/create/posts','CreatePostController');
         //event and bounty//
         Route::get('/event/','BountyController@show')->name('event.show');
         Route::get('/event/detail/{detail}','BountyController@showdetail')->name('event.show.detail');
         Route::get('/event/detail/with/category/{category}','BountyController@showcategorydetail')->name('event.show.category.detail');
         Route::get('/closed/bounty','BountyController@closedbounty')->name('closed.bounty');
         //download file
         Route::get('/file/download/{id}','BountyController@download')->name('file.download');

         Route::post('/report/send','BountyController@sendReport')->name('report.send');
         Route::get('/mark/notification/','BountyController@check_read_notification');


});


// admin routes here

Route::prefix('admin')->namespace('admin')->group(function()
{ 
 Route::middleware('redirectToDashboard')->group(function()
    {
     Route::get('/show/login','LoginController@showloginform')->name('admin.show.login');
	 	 Route::post('/login','LoginController@login')->name('admin.login');
	   Route::get('/show/signup','LoginController@showsignupform')->name('admin.show.signup');
	   Route::post('/signup','LoginController@signup')->name('admin.signup');
   });
     Route::get('/logout','LoginController@logout')->name('admin.logout');

     Route::middleware('admin')->name('admin.')->group(function()
     {
       Route::get('/dashboard','DashboardController@show')->name('dashboard');
       Route::resource('categories','CategoryController');
       Route::resource('posts','PostController');
       Route::get('/pending/post','PostController@pendingpost')->name('pending.post');
       Route::post('/approve/post/{post}','PostController@approvepost')->name('approve.post');
       Route::post('/trash/posts/{post}','PostController@trash')->name('trash.post');
       Route::get('/show/trash','PostController@showtrash')->name('show.trash');
       Route::post('/restore/post/{post}','PostController@restorepost')->name('restore.post');
       //bounty category
       Route::resource('category/bounties','BountyCategoryController');
       Route::get('active/bounty','BountyController@showactivebunty')->name('active.bounty');
       Route::get('pending/bounty','BountyController@showpendingbunty')->name('pending.bounty');
       Route::get('/closed/bounty','BountyController@showexpiredbunty')->name('closed.bounty');
       Route::post('approve/bounty/{bounty}','BountyController@approve')->name('approve.bounty');
       Route::post('multiple/delete','BountyController@massdelete')->name('mass.bounty.delete');
       Route::get('single/delete/{id}','BountyController@singledelete')->name('single.bounty.delete');
       // Route::get('bounties/show','BountyController@index')->name('admin.bounties.index');
       //gallaery here
       Route::resource('gallery-category','GalleryCategoryController');
       // Route::resource('gallery-image','GalleryImageController');
       Route::post('admin/gallery-image/store/{id}','GalleryImageController@store')->name('gallery-image.store');
       Route::get('admin/gallery-image/{gallery_image}','GalleryImageController@show')->name('gallery-image.show');
       Route::post('admin/gallery-image/{gallery_image}','GalleryImageController@destroy')->name('gallery-image.destroy');

   });


});






 // business section route here

  Route::prefix('business')->namespace('business')->name('business.')->middleware('business')->group(function()
  {

     Route::get('/dashboard','DashboardController@index')->name('dashboard');
     Route::get('/profile','BusinessController@profile')->name('profile');
     Route::post('/profile/update/{id}', 'BusinessController@update')->name('profile.update');
    // business post
     Route::get('/post','BlogController@showpost')->name('post');
     Route::get('/singlepost/{post}','BlogController@singlepost')->name('singlepost');
     Route::get('/post/category/{category}','BlogController@category')->name('post.category');
     Route::resource('/create/posts','CreatePostController');
    //business event
     Route::get('/event','EventController@show')->name('event');
     Route::get('/mark/notification/','EventController@check_read_notification');
     Route::get('/rate','EventController@RatingStore');
     Route::get('/rate/check','EventController@CheckIfAlready');

     Route::get('show/hacker/profile/{id}','EventController@showhackerprofile')->name('show.hacker.profile'); 
     Route::post('post/bounty','BountyController@store')->name('bounty.store');

     Route::get('/report/detail/{id}','EventController@showReportDetails')->name('reports.detail');
     Route::get('/report/delete/{id}','EventController@deletereport')->name('delete.report');
     Route::post('/report/delete/mass','EventController@deleteMassreport')->name('delete.mass-report');  



});

 // business route end here



//post is public so rote is made publuc







// Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{

	   use SoftDeletes;
	   
	       protected $fillable=['title','image','description','content','status','category_id','user_id','published_at'];


	       public function category()
	         {
	         	return $this->belongsTo(Category::class);
	         }
             
             public function user()
             {
             	return $this->belongsTo(User::class);
             }

                public function scopeSearched($query)
                  {
                        $search= request()->query('search');

                        if(!$search)
                        {
                           return $query;
                        }


                      return $query->where('title','LIKE',"%{$search}%");
                  }

           
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post; 
use App\Category;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

           
          return view('admin.post.post')->with('posts',Post::where('status','active')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
          return view('admin.post.insertpost')->with('categories',Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)

    {
      
          
            
           $rules=['title'=>'required|unique:posts',

                    'description'=>'required|max:255',
                    'content'=>'required',
                    'image'=>'mimes:jpeg,png,jpg,gif,svg|max:2048|required',
                    'category_id'=>'required',
                    'published_at'=>'required',
                      
           ];
           $message=['description.max'=>'your description is long plz make it short'];

           $this->validate($request,$rules,$message);

            if($request->hasFile('image')) {
            $file = $request->file('image');
            $file_name = time()."_".$file->getClientOriginalName();
            $file_location = public_path('post/img');

            $file->move($file_location, $file_name);
               
            
          }

           Post::create([
                            'title'=>$request->title,
                            'content'=>$request->content,
                            'description'=>$request->description,
                          
                            'user_id'=>auth()->user()->id,
                             'category_id'=>$request->category_id,
                             'status'=>'active',
                             'image'=>$file_name,
                             'published_at'=>$request->published_at





           ]);

          session()->flash('success','post created successfully');
           return redirect(route('admin.posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
          // $posts=Post::findOrFail($id);

        

          return view('admin.post.insertpost')->with('posts',$post)->with('categories',Category::all());

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Post $post)
    {

          $rules=[
                   'file'=>'mimes:jpeg,png,jpg,gif,svg|max:2048',
                    

          ];
          $this->validate($request,$rules);
        
            if(file_exists(public_path().'/post/img/'.$post->image)) 
                {
                 unlink(public_path().'/post/img/'.$post->image);
                } 

        $data=$request->only(['title','description','content','category_id','published_at']);
     
        if($request->hasFile('image'))
             {   $file=$request->file('image');
                $extension=$file->getClientOriginalExtension();
                $filename=time().'.'.$extension;
                $file->move('post/img/',$filename);
                $data['image']=$filename;


             }


          


        $post->update($data);


        session()->flash('success','Post updated successfully');
           return redirect(route('admin.posts.index'));



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post  $post)
    {

        // unlink(public_path().'/post/img/'.$post->image);
        $post->forceDelete(); 

        session()->flash('success','post Deleted successfully');
           return redirect()->back();

    }

    public function pendingpost()
        {
          return view('admin.post.pending')->with('posts',Post::where('status','pending')->get());
       }

        public function approvepost(Post $post)

              {   
                  $data['status']="active";
                  $post->update($data);
                  session()->flash('success','Post has been approved');
                     return view('admin.post.pending')->with('posts',Post::where('status','pending')->get());

              }

          public function trash(Post $post)
            {
                 $data['status']="trash";
                  $post->update($data);
                  session()->flash('success','Post has been trash');
                     return view('admin.post.pending')->with('posts',Post::where('status','pending')->get());


            } 

            public function restorepost(Post $post)
            {
                 $data['status']="active";
                  $post->update($data);
                  session()->flash('success','Post has been restored');
                     return view('admin.post.trash')->with('posts',Post::where('status','trash')->get());


            } 

             public function showtrash()
            {
            $post=Post::where('status','trash')->get();
            return view('admin.post.trash')->with('posts',$post);
             }


             public static function activepost()
             {
                return Post::where('status','active')->count();
             }

             public static function pendingposts()
             {
                return Post::where('status','pending')->count();
             }

             public static function trashpost()
             {
                return Post::where('status','trash')->count();
             }       
   }

app/Http/Controllers/business/BlogController.php
<?php

namespace App\Http\Controllers\business;
use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BlogController extends Controller
{
     public function showpost()
         {  
         	$search=request()->query('search');
         	 if(request()->query('search'))
         	 {  $post=Post::where('title','Like',"%{$search}%")->where('status','active')->simplePaginate(4);

         	 }

         	 else
         	 {
         	$post=Post::where('status','active')->simplePaginate(4);
         	 }
         	return view('front.business.post.post')
         	->with('posts',$post)
         	->with('categories',Category::all());
         }


         public function singlepost(Post $post)
            {
            	return view('front.business.post.singlepost')
            	->with('post',$post)
            	->with('categories',Category::all());
            }

           public function category(Category $category)
              {

              	

              	 return view('front.business.post.category')
              	 ->with('category',$category)
              	 ->with('posts',$category->post()->searched()->simplePaginate(4))
                  ->with('categories',Category::all());

              

                  

              }
}

app/Http/Controllers/business/DashboardController.php
<?php

namespace App\Http\Controllers\business;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
     public function index()
          {
               return view('front.business.dashboard');

          }

}

resources/views/front/business/post/category.blade.php
@extends('layouts.front.business')


    <!-- Navbar -->
 @section('header')
         <header class="header text-center text-white" style="background-image: url({{asset('assets/img/business/bg8.jpg')}})">
      <div class="container">

        <div class="row">
          <div class="col-md-8 mx-auto">

            <h1 >Category:<strong>{{$category->name}}</strong></h1>
            <p class="lead-2 opacity-90 mt-6" style="color: black;"><strong>See the latest blog post of <span class="text-primary" data-typing="@foreach($posts as $post){{$post->title}}, @endforeach" data-back-speed="100"></span></strong></p>

          </div>
        </div>

      </div>
    </header><!-- /.header -->
    <!-- END Header -->

 @endsection

 @section('content')
    <main class="main-content">
      <div class="section bg-gray">
        <div class="container">
          <div class="row">


            <div class="col-md-8 col-xl-9">
              <div class="row gap-y">
            
             @forelse($posts as $post)
                <div class="col-md-6">
                  <div class="card border hover-shadow-6 mb-6 d-block">
                    <a href="{{route('business.singlepost',$post->id)}}"><img class="card-img-top" src="{{asset('post/img/'.$post->image) }}" alt="Card image cap"></a>
                    <div class="p-6 text-center">
                      <p><a class="small-5 text-lighter text-uppercase ls-2 fw-400" >{{$post->category->name}}</a></p>
                      <h5 class="mb-0"><a class="text-dark" href="{{route('business.singlepost',$post->id)}}">{{$post->title}}}</a></h5>
                    </div>
                  </div>
                </div>
                 @empty

                      <p class="text-center">
                       <center> No result found for search......<strong>{{ request()->query('search')}}</strong> </center>
                        
                      </p>
                  @endforelse


               

              </div>

          {{ $posts->appends(['search'=>request()->query('search')])->links()}}
           <!--    <nav class="flexbox mt-30">
                <a class="btn btn-white disabled"><i class="ti-arrow-left fs-9 mr-4"></i> Newer</a>
                <a class="btn btn-white" href="#">Older <i class="ti-arrow-right fs-9 ml-4"></i></a>
              </nav> -->
            </div>



            <div class="col-md-4 col-xl-3">
              <div class="sidebar px-4 py-md-0">

                <h6 class="sidebar-title">Search</h6>
                <form class="input-group" action="#" method="GET">
                  <input type="text" class="form-control" name="search" placeholder="search" value="{{request()->query('search')}}">
                  <div class="input-group-addon">
                    <span class="input-group-text"><i class="ti-search"></i></span>
                  </div>
                </form>

                <hr>

                <h6 class="sidebar-title">Categories</h6>
                <div class="row link-color-default fs-14 lh-24">
                	@foreach($categories as $category)
                  <div class="col-6"><a href="{{route('business.post.category',$category->id)}}">{{$category->name}}</a></div>
                     @endforeach
                </div>

                <hr>

                <h6 class="sidebar-title">Top posts</h6>
                 @foreach($posts as $post)
                <a class="media text-default align-items-center mb-5" href="{{route('hacker.singlepost',$post->id)}}">
                  <img class="rounded w-65px mr-4" src="{{asset('post/img/'.$post->image) }}">
                  <p class="media-body small-2 lh-4 mb-0">{{$post->title}}</p>
                </a>
                @endforeach

                

                <hr>

           
                <h6 class="sidebar-title">About</h6>
                <p class="small-3">Post here is information posted by user hacker and user business as well as supre admin you can see post related to the technology and many other once you post here your post will be queue in admin pannel and until admin approve you can't see your post</p>

              </div>
            </div>

          </div>
        </div>
      </div>
    </main>

 


 @endsection

 @section('css')

 <!--  -->

 @endsection


 @section('script')
   


 @endsection

resources/views/front/business/post/post.blade.php
@extends('layouts.front.business')


    <!-- Navbar -->
 @section('header')
         <header class="header text-center text-white bg-gray" style=" background-color: black;">
      <div class="container">

        <div class="row">
          <div class="col-md-8 mx-auto">

            <h1 style="color: black;">Post</h1>
            <p class="lead-2 opacity-90 mt-6" style="">See the latest blog post of <span class="text-primary" data-typing="@foreach($posts as $post){{$post->title}}, @endforeach" data-back-speed="100"></span></center></h1></p>

          </div>
        </div>

      </div>
    </header><!-- /.header -->
    <!-- END Header -->

 @endsection

 @section('content')
    <main class="main-content">
      <div class="section bg-gray">
        <div class="container">
          <div class="row">


            <div class="col-md-8 col-xl-9">
              <div class="row gap-y">
             
                @forelse($posts as $post)
                <div class="col-md-6">
                  <div class="card border hover-shadow-6 mb-6 d-block">
                    <a href="{{route('business.singlepost',$post->id)}}"><img class="card-img-top" src="{{asset('post/img/'.$post->image) }}" alt="Card image cap"></a>
                    <div class="p-6 text-center">
                      <p><a class="small-5 text-lighter text-uppercase ls-2 fw-400" >{{$post->category->name}}</a></p>
                      <h5 class="mb-0"><a class="text-dark" href="{{route('business.singlepost',$post->id)}}">{{$post->title}}}</a></h5>
                    </div>
                  </div>
                </div>
                 @empty

                      <p class="text-center">
                       <center> No result found for search......<strong>{{ request()->query('search')}}</strong> </center>
                        
                      </p>
                  @endforelse



               

              </div>

          {{ $posts->appends(['search'=>request()->query('search')])->links()}}
           <!--    <nav class="flexbox mt-30">
                <a class="btn btn-white disabled"><i class="ti-arrow-left fs-9 mr-4"></i> Newer</a>
                <a class="btn btn-white" href="#">Older <i class="ti-arrow-right fs-9 ml-4"></i></a>
              </nav> -->
            </div>



            <div class="col-md-4 col-xl-3">
              <div class="sidebar px-4 py-md-0">
                   @if(Auth::user()->hasVerifiedEmail())
                <h6 class="sidebar-title"><a href="{{route('business.posts.create')}}" class="btn btn-primary mb-2">Create post</a></h6>
                @endif
                <h6 class="sidebar-title">Search</h6>
                <form class="input-group" action="{{route('business.post')}}" method="GET">
                  <input type="text" class="form-control" name="search" placeholder="search" value="{{request()->query('search')}}">
                  <div class="input-group-addon">
                    <span class="input-group-text"><i class="ti-search"></i></span>
                  </div>
                </form>

                <hr>

                <h6 class="sidebar-title">Categories</h6>
                <div class="row link-color-default fs-14 lh-24">
                  @foreach($categories as $category)
                  <div class="col-6"><a href="{{route('business.post.category',$category->id)}}">{{$category->name}}</a></div>
                     @endforeach
                </div>

                <hr>

                  <h6 class="sidebar-title">Top posts</h6>
                 @foreach($posts as $post)
                <a class="media text-default align-items-center mb-5" href="{{route('business.singlepost',$post->id)}}">
                  <img class="rounded w-65px mr-4" src="{{asset('post/img/'.$post->image) }}">
                  <p class="media-body small-2 lh-4 mb-0">{{$post->title}}</p>
                </a>
                @endforeach

                <hr>

           

                <h6 class="sidebar-title">About</h6>
                <p class="small-3">Post here is information posted by user hacker and user business as well as supre admin you can see post related to the technology and many other once you post here your post will be queue in admin pannel and until admin approve you can't see your post</p>



              </div>
            </div>

          </div>
        </div>
      </div>
    </main>

 


 @endsection

 @section('css')

 <!--  -->

 @endsection


 @section('script')
   


 @endsection

resources/views/front/business/post/singlepost.blade.php
@extends('layouts.front.business')


@section('header')
  <header class="header text-center text-white" style=" background-color: white;" data-overlay="5">
      <div class="container text-center">

        <div class="row h-100">
          <div class="col-lg-8 mx-auto align-self-center">

            <p class="opacity-70 text-uppercase small ls-1">{{$post->category->name}}</p>
            <h1 class="display-4 mt-7 mb-8">{{$post->title}}</h1>
            <p><span class="opacity-70 mr-1">By</span> <a class="text-white" href="#">{{$post->user->name}}</a></p>
            <p>
             @if($post->user->role=='business')
              
               <img class="avatar avatar-sm" src="{{ asset('profile/business/img/'.Auth::user()->userbusiness->image) }}"  alt="..."></p>
               
                @else
                <img class="avatar avatar-sm" src="{{asset('assets/img/avatar/2.jpg')}}" alt="..."></p>
                @endif
          </div>

          <div class="col-12 align-self-end text-center">
            <a class="scroll-down-1 scroll-down-white" href="#section-content"><span></span></a>
          </div>

        </div>

      </div>
    </header><!-- /.header -->

@endsection

@section('content')
<main class="main-content">


      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Blog content
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <div class="section" id="section-content">
        <div class="container">
                <h3>Description</h3>
                {{$post->description}}
                <hr>
               <center><img src="{{asset('post/img/'.$post->image) }}" height="500" width="500"></center> 
                <hr>

       <h3>Content</h3>
         
                {!! $post->content !!}


         
             
              <div class="gap-xy-2 mt-6">
                
                 @foreach($categories as $category)
                <a class="badge badge-pill badge-secondary" href="{{route('business.post.category',$category->id)}}">{{$category->name}}</a>
               @endforeach
              </div>
              

            </div>
          </div>


    



      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Comments
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <div class="section bg-gray">
        <div class="container">

          <div class="row">
            <div class="col-lg-8 mx-auto">

          


              <hr>
              <div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = "{{config('app.url')}}/blog/posts/{{$post->id}}";  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = "{{$post->id}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://saas-blog-dqkglwljlo.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            


        
            </div>
          </div>

        </div>
      </div>



    </main>


@endsection